language: java
sudo: false
before_install:
- cd etc/build
script: ant war
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key:
    secure: fd1Z3+fvgLqESquu6k88FKaZJ/DwcGwIimU+YyheQDYgAs+IvOFnXTfk3+j32PstofMP5BLpXeDCtIqUSEA5mygktLTHs/52s6Q6F3XocBLVD5PSK9aYKnuIeDHAC/h+UUwoOOAZTWqhmHZd4XnpeywTqE/HLPfJf3P/RYZcV/NDXXcCvxDuBz80KV9fUJAC1NpQya/OLbjWa26ncAnyQJt2BLEpCMcHOAErhP43D7j6eZofK/sW3p5i3phnIY7kIq8dGWeY9x1vJjqxYoFNJ9dEAvYpT63VrZbQsXY1eYFK8h+l3bjQCike2VCVn8QnIbqhlbBzNpetEa/Bm9vTUVVe0jp1QU4wqW0voicRmkS0nl5y+yYt3KXSN1yKduPssYLPwtmKoROcGlUoO3l/a3t3zHHWe0pzb529CX6MdlNBsRIu9ncUeBy43+U7acBkDwpVyabdbUKHlY+J8Z5UC7QkrIfp7LPcnU9Dx1ErTDDKITyXYc56ZjN7fpxQI1dPDDK8beeEIfr6nD/pCBsW4kBSNDfE7yizbZO1mjF1RFpBObIEV3P9PI+CWQXODap9FhLqg3tsRY4vFVWGk/eseATEROS1NWyzsZWRqic2PVCbO8lqh8vZB4DKuQYgLLBPj8XPTuYbHNcRxzUyFJrXtTtqLa7WAnX/OtekOLOLruk=
  file: build/draw.war
  skip_cleanup: true
  on:
    repo: ergonlogic/drawio
